### ISSUE TITLE
Bundled Source?

### ISSUE THREAD

**Issue by DennisSmolek** [AndrewSink/3D-Low-Poly-Generator#3]
Hey Andrew, I was trying to play with the tool to see how it works but in: https://github.com/AndrewSink/3D-Low-Poly-Generator/commit/d86707cfcf083784740b42823b37056b576e0d7a

you've removed the src folder.

Now I understand as a deployment build that step would be done but I'm not sure why on this repo.. Are you closing it or obscuring it on purpose?

Was it on accident?

As of now, unless they go back through your commits (95% wont) What they have here is a basic web page with the heart of your awesome work in those bundles..😕

**Comment by AndrewSink** [comment]
Great catch, @DennisSmolek! Looks like I forgot to upload it with the latest version. I'll make sure to include it with the next version I release. Thanks!

**Comment by AndrewSink** [comment]
FYI @DennisSmolek: This has been fixed with v1.2.2! Thanks again for flagging!

**Comment by tinkerology** [comment]
Do you have a package.json that you could push up too?
