### ISSUE TITLE
Triangle reduction over 50%?

### ISSUE THREAD

**Issue by INeDiA** [AndrewSink/3D-Low-Poly-Generator#4]
I don't know if it's a bug or a feature™, but the slider on the testing website won't go over 50%

**Comment by AndrewSink** [comment]
The processing time increases significantly when doing large decimations, so the total triangle reduction amount is limited to  50%. This is an arbitrary number, but it worked well during testing and kept the total time to generally <1 minute for processing. 

Great catch, and thanks for flagging!
